apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
    env: production
spec:
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 6