apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      name: db-noticias-pod
      labels:
        app: db-noticias
    spec:
      containers:
      - name: db-container
        image: aluracursos/mysql-db:1
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: db-configmap